sudo: required

language: c

services:
  - docker

before_install:
  - docker pull taotaohsu/tig-deb-docker

script:
  - docker run -v $TRAVIS_BUILD_DIR:/tmp/build_dir taotaohsu/tig-deb-docker /bin/bash -c "cd /tmp/build_dir && make"
  - make upload
